spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gdgoc_report
    username: gdgoc
    password: 1q2w3e4r
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
